# Generated by Django 3.1.7 on 2021-03-20 02:20

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    GROUPS = ['admin', 'employee']

    for group in GROUPS:
        Group.objects.using(db_alias).get_or_create(name=group)


def create_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias

    try:
        user = User(username='admin', email='admin@stickboy.com', is_staff=False, is_superuser=False)
        user.password = make_password('admin')
        user.save(using=db_alias)

        my_group = Group.objects.get(name='admin') 
        my_group.user_set.add(user)
    except Exception as e:
        print(e)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user'),
    ]

    operations = [
        migrations.RunPython(create_groups),
        migrations.RunPython(create_admin_user),
    ]
